# Generated by Django 4.2.6 on 2024-02-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
